// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import BookingformController from "./bookingform_controller"
application.register("bookingform", BookingformController)

import DisplayBookingsController from "./display_bookings_controller"
application.register("display-bookings", DisplayBookingsController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import MapController from "./map_controller"
application.register("map", MapController)
